language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
 - pip install -r requirements.txt
 - python setup.py install
 - pip install python-coveralls
 - pip install coverage
# command to run tests
script: nosetests --with-coverage -w pyglet_helper
after_success:
 - coveralls
